// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NttDataTest.Persistence.Transaction;

namespace NttDataTest.Persistence.Transaction.Migrations
{
    [DbContext(typeof(TransactionDataContext))]
    partial class TransactionDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NttDataTest.Domain.Transaction.Movimientos", b =>
                {
                    b.Property<Guid>("MovimientoGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CuentaGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SaldoDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMovimiento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovimientoGuid");

                    b.ToTable("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
